// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChwBOjYfZkA9lsgekjL6c0sdY3itdoe6A',
    appId: '1:542867718925:web:e96c131d3b18510e1d2644',
    messagingSenderId: '542867718925',
    projectId: 'pawfectcare-1234',
    authDomain: 'pawfectcare-1234.firebaseapp.com',
    databaseURL: 'https://pawfectcare-1234-default-rtdb.firebaseio.com',
    storageBucket: 'pawfectcare-1234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0sC4f4XelbC8QX86qx245NBaEp44BuLk',
    appId: '1:542867718925:android:649dcbcab235c7d51d2644',
    messagingSenderId: '542867718925',
    projectId: 'pawfectcare-1234',
    databaseURL: 'https://pawfectcare-1234-default-rtdb.firebaseio.com',
    storageBucket: 'pawfectcare-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRC7M-kERF3K2IGODdss1nmJ0UD4HZh04',
    appId: '1:542867718925:ios:33968e45199019801d2644',
    messagingSenderId: '542867718925',
    projectId: 'pawfectcare-1234',
    databaseURL: 'https://pawfectcare-1234-default-rtdb.firebaseio.com',
    storageBucket: 'pawfectcare-1234.firebasestorage.app',
    iosBundleId: 'com.example.pawfectcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRC7M-kERF3K2IGODdss1nmJ0UD4HZh04',
    appId: '1:542867718925:ios:33968e45199019801d2644',
    messagingSenderId: '542867718925',
    projectId: 'pawfectcare-1234',
    databaseURL: 'https://pawfectcare-1234-default-rtdb.firebaseio.com',
    storageBucket: 'pawfectcare-1234.firebasestorage.app',
    iosBundleId: 'com.example.pawfectcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChwBOjYfZkA9lsgekjL6c0sdY3itdoe6A',
    appId: '1:542867718925:web:a86f53ded79704b61d2644',
    messagingSenderId: '542867718925',
    projectId: 'pawfectcare-1234',
    authDomain: 'pawfectcare-1234.firebaseapp.com',
    databaseURL: 'https://pawfectcare-1234-default-rtdb.firebaseio.com',
    storageBucket: 'pawfectcare-1234.firebasestorage.app',
  );

}